# Generated by Django 4.1.2 on 2022-10-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stageName', models.CharField(max_length=70, unique=True)),
                ('socialLink', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'artists',
                'ordering': ['stageName'],
            },
        ),
    ]
