# Generated by Django 4.1.2 on 2022-10-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Approved',
            field=models.BooleanField(default=False, help_text="If the album's name doesn't contain inappropriate expressions, approve it."),
        ),
    ]
