# Generated by Django 4.1.2 on 2022-10-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'songs',
            },
        ),
    ]
