# Generated by Django 4.1.2 on 2022-10-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
