# Generated by Django 4.1.2 on 2022-10-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(default='New Song', upload_to='musics/'),
        ),
    ]
