# Generated by Django 4.1.2 on 2022-10-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(default='New Song', help_text='Allowed type - .mp3, .wav,', upload_to='musics/'),
        ),
    ]
