# Generated by Django 4.1.2 on 2022-10-21 07:24

import albums.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_song_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(default='New Song', help_text='Allowed type - .mp3, .wav,', upload_to='musics/', validators=[albums.models.fileExtensionValidator]),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
